name: Deploy via Shell Script

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Call Server Script
    runs-on: ubuntu-latest
    steps:
    - name: Execute deploy.sh via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        # 这里只需要一行命令：执行脚本
        script: /www/wwwroot/deploy.sh